### ISSUE TITLE
Yüklenmeyen resimler

### ISSUE THREAD

**Issue by obk** [omergulcicek/omergulcicek.com#3]
[Ana Sayfa](https://user-images.githubusercontent.com/68072031/103970801-24c9d880-517a-11eb-8fb8-1923be96eacf.png) ve [Hakkımda](https://user-images.githubusercontent.com/68072031/103970786-1b407080-517a-11eb-8dda-ca7a5f52733e.png) sayfalarında yüklenmeyen resimler var.

**Comment by omergulcicek** [comment]
Oralarda resim yok, ileride resim eklersem nasıl durur gibisinden gri bir alan eklemiştim :) 
Canlıya çıkarken gizlemeyi unutmuşum. Şimdi tekrar güncelledim ve bu kısımları gizledim.
